stryker4s {
  mutate = [
    "**/main/scala/**/*.scala",
    "!**/Main.scala",
    "!**/kafka/MoveValidatorStream.scala"
  ]

  scala-dialect = "scala3"

  reporters = ["console", "html"]

  thresholds {
    high = 80
    low = 60
    break = 0
  }

  excluded-mutations = []
}
