addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"    % "0.14.6")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.5.6")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"   % "2.4.4")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.1.233")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"    % "2.3.1")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s"  % "0.20.4")
